//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Insuree
    {
      
        public int Id { get; set; }
        [Display(Name = "Nombre")]
        public string FirstName { get; set; }
        [Display(Name = "Apellido")]
        public string LastName { get; set; }
        [Display(Name = "E-mail")]
        public string EmailAddress { get; set; }

        [Display(Name = "Fecha de nacimiento")]
        public System.DateTime DateOfBirth { get; set; }
       
        public int CarYear { get; set; }
       

        public string CarMake { get; set; }
        

        public string CarModel { get; set; }
        

        public bool DUI { get; set; }
        

        public int SpeedingeTickets { get; set; }
        [Display(Name = "Multas")]
        public bool CoverageType { get; set; }
        [Display(Name = "Cotizacion")]
        public decimal Quote { get; set; }
    }
}
